name: Domain Decomposition Toolkit CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        shell: bash
        run: |
          sudo apt-get install -y cmake libboost-program-options-dev libhdf5-mpi-dev libcurl4-nss-dev
          git clone https://github.com/catchorg/Catch2.git
          cd Catch2
          cmake -DBUILD_TESTING=OFF -Bbuild -S.
          sudo cmake --build build --config Release --target install
          cd ..
          git clone https://github.com/trilinos/Trilinos.git
          cd Trilinos
          cmake \
          -DTPL_ENABLE_MPI:BOOL=ON \
          -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
          -DTrilinos_ENABLE_Zoltan:BOOL=ON \
          -DTrilinos_ENABLE_Fortran:BOOL=OFF \
          -DZoltan_ENABLE_EXAMPLES:BOOL=OFF \
          -DZoltan_ENABLE_TESTS:BOOL=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -Bbuild -S.
          sudo cmake --build build --config Release --target install
          cd ..
          git clone -b checkpoint.1.12.3 https://github.com/Parallel-NetCDF/PnetCDF.git
          cd PnetCDF
          autoreconf -i
          CXX=mpicxx CC=mpicc ./configure --disable-fortran --enable-shared
          make
          sudo make install
          cd ..
          git clone -b v4.8.1 https://github.com/Unidata/netcdf-c.git
          cd netcdf-c
          cmake \
          -DENABLE_PNETCDF=ON \
          -DCMAKE_C_COMPILER=mpicc \
          -DCMAKE_CXX_COMPILER=mpicxx \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_TESTS=OFF \
          -DENABLE_PARALLEL_TESTS=OFF \
          -Bbuild -S.
          sudo cmake --build build --config Release --target install
          cd ..
      - name: Configure
        shell: bash
        run: |
          cmake -G "Unix Makefiles" -Bbuild -S.
      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release
      - name: Run unit tests
        shell: bash
        run: |
          cd build
          ctest -V

  build-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install cmake
          brew install catch2
          brew install boost
          brew install hdf5-mpi
          brew install pnetcdf
          git clone https://github.com/trilinos/Trilinos.git
          cd Trilinos
          cmake \
          -DTPL_ENABLE_MPI:BOOL=ON \
          -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
          -DTrilinos_ENABLE_Zoltan:BOOL=ON \
          -DTrilinos_ENABLE_Fortran:BOOL=OFF \
          -DZoltan_ENABLE_EXAMPLES:BOOL=OFF \
          -DZoltan_ENABLE_TESTS:BOOL=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -Bbuild -S.
          sudo cmake --build build --config Release --target install
          cd ..
          git clone -b v4.8.1 https://github.com/Unidata/netcdf-c.git
          cd netcdf-c
          cmake \
          -DENABLE_PNETCDF=ON \
          -DCMAKE_C_COMPILER=mpicc \
          -DCMAKE_CXX_COMPILER=mpicxx \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_TESTS=OFF \
          -DENABLE_PARALLEL_TESTS=OFF \
          -Bbuild -S.
          sudo cmake --build build --config Release --target install
          cd ..
      - name: Configure
        run: |
          cmake -Bbuild -S.
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Run unit tests
        run: |
          cd build
          ctest -V
