name: 'Domain Decomposition Toolkit CI'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nextsimhub/nextsimdg-dev-env:latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        shell: bash
        run: |
          cmake -G "Unix Makefiles" -Bbuild -S.
      - name: Build
        shell: bash
        run: |
          cmake --build build --config Release
      - name: Run unit tests
        shell: bash
        run: |
          cd build
          ctest -V

  build-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install cmake
          brew install catch2
          brew install boost
          brew install hdf5-mpi
          brew install netcdf
          brew install pnetcdf
          brew install trilinos
      - name: Configure
        run: |
          cmake -Bbuild -S.
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Run unit tests
        run: |
          cd build
          ctest -V
