name: 'Domain Decomposition Toolkit CI'
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build-on-ubuntu:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/nextsimhub/nextsimdg-dev-env:latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        shell: bash
        run: |
          . /opt/spack-environment/activate.sh
          cmake -G "Unix Makefiles" -Bbuild -S.
      - name: Build
        shell: bash
        run: |
          . /opt/spack-environment/activate.sh
          cmake --build build --config Release
      - name: Run unit tests
        shell: bash
        run: |
          . /opt/spack-environment/activate.sh
          cd build
          ctest -V

  build-on-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          brew install open-mpi
          brew install netcdf
          brew install netcdf-cxx
          brew install boost
          brew install cmake
          brew install catch2
          git clone https://github.com/trilinos/Trilinos.git
          cd Trilinos
          cmake \
          -DTPL_ENABLE_MPI:BOOL=ON \
          -DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
          -DTrilinos_ENABLE_Zoltan:BOOL=ON \
          -DTrilinos_ENABLE_Fortran:BOOL=OFF \
          -DZoltan_ENABLE_EXAMPLES:BOOL=OFF \
          -DZoltan_ENABLE_TESTS:BOOL=OFF \
          -DBUILD_SHARED_LIBS=ON \
          -Bbuild -S.
          sudo cmake --build build --config Release --target install
      - name: Configure
        run: |
          cmake -Bbuild -S.
      - name: Build
        run: |
          cmake --build build --config Release
      - name: Run unit tests
        run: |
          cd build
          ctest -V
